export const GESTURE = {
  ITEM_DRAG_DELAY_MS: 500,
  CATEGORY_DRAG_DELAY_MS: 500,
  CATEGORY_DRAG_DELAY_EDIT_MS: 500,
  CATEGORY_EDIT_DELAY_MS: 2000,
  MOVE_TOLERANCE_PX: 20,
  HORIZONTAL_SWIPE_PX: 22,
} as const;
